apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "kernel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  progressDeadlineSeconds: 180
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  {{ if .Values.podAntiAffinity.enabled }}
  spec:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - {{ .Chart.Name }}
          topologyKey: "kubernetes.io/hostname"
  {{ end }}
  template:
    metadata:
      {{ if .Values.kube2iam.enabled }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.app.iam.role }}
      {{ end }}
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: init-pg
        image: postgres:9.3-alpine
        command: ['bash', '-c', './scripts/init.sh']
        env:
        - name: PGHOST
          valueFrom :
            secretKeyRef:
              name: {{ .Values.app.db.secret }}
              key: host
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.db.secret }}
              key: user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.db.secret }}
              key: password
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-password
        - name: DB_USERNAME
          value: {{ .Values.app.db.user }}
        - name: DB_NAME
          value: {{ .Values.app.db.name }}
        volumeMounts:
        - mountPath: /scripts
          name: init-pg-config
        {{ if .Values.provider.gcp }}
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
        {{ end }}
      - name: init-kernel-setup
        image: "{{ .Values.app.repository }}:{{ .Values.app.tag | default .Chart.Version }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        command: ['bash', '-c', '/scripts/shell/setup.sh']
        env:
        - name: ADMIN_USERNAME
          value: {{ .Values.app.admin_user }}
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-admin-password
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-admin-token
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-password
        - name: PGUSER
          value: {{ .Values.app.db.user }}
        - name: PGPORT
          value: {{ .Values.app.db.port | default 5432 | quote }}
        - name: PGHOST
          value: {{ .Values.app.db.host }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-password
        - name: DEBUG
          value: {{ if .Values.debug }}"1"{{ else }}""{{ end }}
        - name: CAS_SERVER_URL
          value: {{ .Values.ums_url }}
        - name: CSRF_COOKIE_DOMAIN
          value: {{ .Values.domain }}
        - name: CSRF_TRUSTED_ORIGINS
          value: .{{ .Values.domain }}
        - name: HOSTNAME
          value: {{ .Values.app.url }}
        - name: DJANGO_STORAGE_BACKEND
          value: {{ .Values.app.storage.backend }}
        - name: BUCKET_NAME
          value: {{ .Values.app.storage.bucket.name }}
        {{ if .Values.provider.aws }}
        - name: AWS_S3_REGION_NAME
          value: {{ .Values.app.storage.bucket.region }}
        - name: AWS_S3_ENDPOINT_URL
          value: s3.{{ .Values.app.storage.bucket.region }}.amazonaws.com
        - name: AWS_DEFAULT_ACL
          value: {{ .Values.app.storage.bucket.default_acl }}
        {{ end }}
        {{ if .Values.provider.gcp }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: {{ .Values.app.storage.bucket.credentialsPath }}
        {{ end }}
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-secret-key
        - name: DB_USERNAME
          value: {{ .Values.app.db.user }}
        - name: DB_NAME
          value: {{ .Values.app.db.name }}
        {{ if .Values.app.exm.enabled }}
        - name: REDIS_DB
          value: "0"
        - name: REDIS_HOST
          value: {{ .Values.app.exm.redis.service }}
        - name: REDIS_PORT
          value: {{ .Values.app.exm.redis.port | quote }}
        - name: WRITE_ENTITIES_TO_REDIS
          value: "false"
        {{ end }}
        - name: WEB_SERVER_PORT
          value: {{ quote .Values.app.port }}
        volumeMounts:
        - mountPath: /scripts/shell
          name: init-setup-sh
        {{ if .Values.provider.gcp }}
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
        {{ end }}
      containers:
      {{ if .Values.provider.gcp }}
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances={{ .Values.database.instance }}=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      {{ end }}
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/static
          name: static-assets-volume
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
      - name: kernel
        image: "{{ .Values.app.repository }}:{{ .Values.app.tag | default .Chart.Version }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        args:
        - {{ .Values.app.command }}
        ports:
        - name: http
          containerPort: {{ .Values.app.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.app.livenessProbe.path }}
            port: http
            httpHeaders:
            - name: X-Kubernetes-Health-Check
              value: livenessProbe
          initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.app.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.app.readinessProbe.path }}
            port: http
            httpHeaders:
            - name: X-Kubernetes-Health-Check
              value: readinessProbe
          initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.app.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
        env:
        - name: DEBUG
          value: {{ if .Values.debug }}"1"{{ else }}""{{ end }}
        - name: GATEWAY_SERVICE_ID
          value: {{ .Values.app.gateWay.serviceId }}
        - name: GATEWAY_PUBLIC_REALM
          value: "{{ .Values.app.gateWay.gatewayPublicRealm }}"
        - name: DEFAULT_REALM
          value: "{{ .Values.app.gateWay.defaultRealm }}"
        - name: KEYCLOAK_SERVER_URL
          value: {{ .Values.app.keycloak.externalUrl }}
        - name: KEYCLOAK_CLIENT_ID
          value: {{ .Values.app.keycloak.clientId }}
        - name: CAS_SERVER_URL
          value: {{ .Values.ums_url }}
        - name: CSRF_COOKIE_DOMAIN
          value: {{ .Values.domain }}
        - name: CSRF_TRUSTED_ORIGINS
          value: .{{ .Values.domain }}
        - name: HOSTNAME
          value: {{ .Release.Name }}.{{ .Values.domain }}
        - name: DJANGO_STORAGE_BACKEND
          value: {{ .Values.app.storage.backend }}
        - name: BUCKET_NAME
          value: {{ .Values.app.storage.bucket.name }}
        {{ if .Values.provider.aws }}
        - name: AWS_S3_REGION_NAME
          value: {{ .Values.app.storage.bucket.region }}
        - name: AWS_DEFAULT_ACL
          value: {{ .Values.app.storage.bucket.default_acl }}
        {{ end }}
        {{ if .Values.app.caching.enabled }}
        - name: DJANGO_USE_CACHE
          value: "true"
        - name: REDIS_DB_CACHEOPS
          value: "1"
        {{ end }}
        {{ if .Values.app.exm.enabled }}
        - name: REDIS_DB
          value: "0"
        - name: REDIS_HOST
          value: {{ .Values.app.exm.redis.service }}
        - name: REDIS_PORT
          value: {{ .Values.app.exm.redis.port | quote }}
        - name: WRITE_ENTITIES_TO_REDIS
          value: "false"
        {{ end }}
        {{ if .Values.sentry.enabled }}
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: sentry-dsn
        {{ end }}
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-secret-key
        - name: ADMIN_USERNAME
          value: {{ .Values.app.admin_user }}
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-admin-password
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-admin-token
        - name: AETHER_KERNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-admin-token
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-password
        - name: PGUSER
          value: {{ .Values.app.db.user }}
        - name: PGPORT
          value: {{ .Values.app.db.port | default 5432 | quote }}
        - name: PGHOST
          value: {{ .Values.app.db.host }}
        - name: DB_NAME
          value: {{ .Values.app.db.name }}
        - name: TESTING
          value: {{ quote .Values.testing }}
        {{ if .Values.app.exm.enabled }}
        - name: REDIS_DB
          value: "0"
        - name: REDIS_HOST
          value: {{ .Values.app.exm.redis.service }}
        - name: REDIS_PORT
          value: {{ .Values.app.exm.redis.port | quote }}
        - name: WRITE_ENTITIES_TO_REDIS
          value: "false"
        {{ end }}
        {{ if .Values.provider.gcp }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: {{ .Values.app.storage.bucket.credentialsPath }}
        {{ end }}
        # `WEB_SERVER_PORT` is kept around for compatibility with the old tests,
        # which are using different ports in different environments. Once all
        # tests have been updated to run inside the cluster, `WEB_SERVER_PORT`
        # can be removed.
        - name: WEB_SERVER_PORT
          value: {{ quote .Values.app.port }}
        - name: UWSGI_THREADS
          value: {{ .Values.app.uwsgi.threads | quote }}
        volumeMounts:
        - mountPath: /var/www/static
          name: static-assets-volume
        {{ if .Values.provider.gcp }}
        - mountPath: /secrets/gcp
          name: google-bucket-credentials
          readOnly: true
        {{ end }}
        {{ if .Values.imagePullSecrets.enabled }}
        imagePullSecrets:
          - name: {{ .Values.imagePullSecrets.name }}
        {{ end }}
      volumes:
      - name: static-assets-volume
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: {{ .Chart.Name }}-nginx-config
      - name: init-pg-config
        configMap:
          name: {{ .Chart.Name }}-init-pg-config
          defaultMode: 0744
      - name: init-setup-sh
        configMap:
          name: {{ .Chart.Name }}-setup-sh
          defaultMode: 0744
      {{ if .Values.provider.gcp }}
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: google-bucket-credentials
        secret:
          secretName: {{ .Values.app.storage.bucket.credentialsSecret }}
      {{ end }}
