apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ template "kernel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  progressDeadlineSeconds: 180
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: init-pg
        image: postgres:9.3-alpine
        command: ['bash', '-c', './scripts/init.sh']
        env:
        - name: PGHOST
          valueFrom :
            secretKeyRef:
              name: {{ .Values.app.db.secret }}
              key: host
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.db.secret }}
              key: user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.db.secret }}
              key: password
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-password
        - name: DB_USERNAME
          value: {{ .Values.app.db.user }}
        - name: DB_NAME
          value: {{ .Values.app.db.name }}
        volumeMounts:
        - mountPath: /scripts
          name: init-pg-config
        {{ if .Values.provider.gcp }}
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
        {{ end }}
      - name: init-kernel-setup
        image: "{{ .Values.app.repository }}:{{ .Values.app.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        args:
          - {{ .Values.app.setup_command }}
        env:
        - name: ADMIN_USERNAME
          value: {{ .Values.app.admin_user }}
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-admin-password
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: admin-token
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-password
        - name: PGUSER
          value: {{ .Values.app.db.user }}
        - name: PGPORT
          value: {{ .Values.app.db.port | default 5432 | quote }}
        - name: PGHOST
          value: {{ .Values.app.db.host }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-password
        - name: DEBUG
          value: {{ if .Values.debug }}"1"{{ else }}""{{ end }}
        - name: CAS_SERVER_URL
          value: {{ .Values.ums_url }}
        - name: CSRF_COOKIE_DOMAIN
          value: {{ .Release.Name }}.{{ .Values.domain }}
        - name: CSRF_TRUSTED_ORIGINS
          value: {{ .Release.Name }}.{{ .Values.domain }}
        - name: HOSTNAME
          value: {{ .Release.Name }}.{{ .Values.domain }}
        - name: DJANGO_STORAGE_BACKEND
          value: {{ .Values.app.storage.backend }}
        - name: BUCKET_NAME
          value: {{ .Values.app.storage.bucket }}
        {{ if .Values.provider.gcp }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: {{ .Values.app.storage.bucket.credentialsPath }}
        {{ end }}
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-secret-key
        - name: DB_USERNAME
          value: {{ .Values.app.db.user }}
        - name: DB_NAME
          value: {{ .Values.app.db.name }}
        - name: KERNEL_READONLY_DB_USERNAME
          value: {{ .Values.app.db.readonly_user }}
        - name: KERNEL_READONLY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-readonly-db-password
        - name: WEB_SERVER_PORT
          value: {{ quote .Values.app.port }}
      - name: init-kernel-create-readonly-user
        image: "{{ .Values.kernel.repository }}:{{ .Values.kernel.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        command: ['python', '/code/sql/create_readonly_user.py']
        env:
        - name: ADMIN_USERNAME
          value: {{ .Values.app.admin_user }}
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-admin-password
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: admin-token
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-password
        - name: PGUSER
          value: {{ .Values.app.db.user }}
        - name: PGPORT
          value: {{ .Values.app.db.port | default 5432 | quote }}
        - name: PGHOST
          value: {{ .Values.app.db.host }}
        - name: DB_USERNAME
          value: {{ .Values.app.db.user }}
        - name: DB_NAME
          value: {{ .Values.app.db.name }}
        - name: KERNEL_READONLY_DB_USERNAME
          value: {{ .Values.app.db.readonly_user }}
        - name: KERNEL_READONLY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-readonly-db-password
        - name: WEB_SERVER_PORT
          value: {{ quote .Values.app.port }}
        - name: DEBUG
          value: {{ if .Values.debug }}"1"{{ else }}""{{ end }}
        - name: CAS_SERVER_URL
          value: {{ .Values.ums_url }}
        - name: CSRF_COOKIE_DOMAIN
          value: {{ .Values.domain }}
        - name: CSRF_TRUSTED_ORIGINS
          value: .{{ .Values.domain }}
        - name: HOSTNAME
          value: {{ .Release.Name }}.{{ .Values.domain }}
        - name: DJANGO_STORAGE_BACKEND
          value: {{ .Values.app.storage.backend }}
        - name: BUCKET_NAME
          value: {{ .Values.app.storage.bucket.name }}
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-secret-key
        volumeMounts:
        - mountPath: /scripts/python
          name: init-py-config
        - mountPath: /scripts
          name: init-py-config-sh
        {{ if .Values.provider.gcp }}
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
        {{ end }}
      containers:
      {{ if .Values.provider.gcp }}
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances={{ .Values.database.instance }}=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      {{ end }}
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/static
          name: static-assets-volume
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
      - name: kernel
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        args:
        - {{ .Values.app.command }}
        ports:
        - name: http
          containerPort: {{ .Values.app.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
            httpHeaders:
            - name: X-Kubernetes-Health-Check
              value: livenessProbe
            - name: Host
              value: {{ .Release.Name }}.{{ .Values.domain }}
        readinessProbe:
          httpGet:
            path: /health
            port: http
            httpHeaders:
            - name: X-Kubernetes-Health-Check
              value: readinessProbe
            - name: Host
              value: {{ .Release.Name }}.{{ .Values.domain }}
        env:
        - name: DEBUG
          value: {{ if .Values.debug }}"1"{{ else }}""{{ end }}
        - name: CAS_SERVER_URL
          value: {{ .Values.ums_url }}
        - name: CSRF_COOKIE_DOMAIN
          value: {{ .Release.Name }}.{{ .Values.domain }}
        - name: CSRF_TRUSTED_ORIGINS
          value: {{ .Release.Name }}.{{ .Values.domain }}
        - name: HOSTNAME
          value: {{ .Release.Name }}.{{ .Values.domain }}
        - name: DJANGO_STORAGE_BACKEND
          value: {{ .Values.app.storage.backend }}
        - name: BUCKET_NAME
          value: {{ .Values.app.storage.bucket }}
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-secret-key
        - name: ADMIN_USERNAME
          value: {{ .Values.app.admin_user }}
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-admin-password
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: admin-token
        - name: AETHER_KERNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-token
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-password
        - name: PGUSER
          value: {{ .Values.app.db.user }}
        - name: PGPORT
          value: {{ .Values.app.db.port | default 5432 | quote }}
        - name: PGHOST
          value: {{ .Values.app.db.host }}
        - name: DB_NAME
          value: {{ .Values.app.db.name }}
        - name: KERNEL_READONLY_DB_USERNAME
          value: {{ .Values.app.db.readonly_user }}
        - name: KERNEL_READONLY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-readonly-db-password
        - name: TESTING
          value: {{ quote .Values.testing }}
        # `WEB_SERVER_PORT` is kept around for compatibility with the old tests,
        # which are using different ports in different environments. Once all
        # tests have been updated to run inside the cluster, `WEB_SERVER_PORT`
        # can be removed.
        - name: WEB_SERVER_PORT
          value: {{ quote .Values.app.port }}
        volumeMounts:
        - mountPath: /var/www/static
          name: static-assets-volume
        {{ if .Values.provider.gcp }}
        - mountPath: /secrets/gcp
          name: google-bucket-credentials
          readOnly: true
        {{ end }}
      volumes:
      - name: static-assets-volume
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: {{ .Release.Name }}-nginx-config
      - name: init-pg-config
        configMap:
          name: {{ .Release.Name }}-init-pg-config
          defaultMode: 0744
      {{ if .Values.provider.gcp }}
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: google-bucket-credentials
        secret:
          secretName: {{ .Values.app.storage.bucket.credentialsSecret }}
      {{ end }}
