{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "kernel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.kernel.url | quote }}
  rules:
    - host: {{ .Values.kernel.url | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Chart.Name }}
              servicePort: 80
{{- end }}
