apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-py-config-sh
data:
{{- if .Values.provider.gcp }}
  create_ro_user.sh: |
    #!/bin/sh
    apk add --no-cache wget ca-certificates && update-ca-certificates
    wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /cloud_sql_proxy
    chmod +x /cloud_sql_proxy
    echo 8.8.8.8 >>/etc/resolv.conf
    echo "starting proxy in background"
    /cloud_sql_proxy -instances={{ .Values.database.instance }}=tcp:5432 -credential_file=/secrets/cloudsql/credentials.json &
    PROXY_PID=$!
    sleep 5

    python ./scripts/python/create_ro_user.py

    sleep 5

    echo "stopping proxy"
    kill $PROXY_PID

{{ else }}
  init.sh: |
    #!/bin/sh

    python ./scripts/python/create_ro_user.py
{{- end -}}
