apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-setup-sh
data:
{{- if .Values.provider.gcp }}
  setup.sh: |
    #!/bin/bash

    set -ex

    wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /cloud_sql_proxy
    chmod +x /cloud_sql_proxy
    echo 8.8.8.8 >>/etc/resolv.conf
    echo "starting proxy in background"
    /cloud_sql_proxy -instances={{ .Values.database.instance }}=tcp:5432 -credential_file=/secrets/cloudsql/credentials.json &
    PROXY_PID=$!
    sleep 5

    ./entrypoint.sh setup

    sleep 5

    echo "stopping proxy"
    kill $PROXY_PID

{{ else }}
  setup.sh: |
    #!/bin/bash

    set -ex

    ./entrypoint.sh setup
{{- end -}}
