apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-create-readonly-user-sh
data:
{{- if .Values.provider.gcp }}
  create_ro_user.sh: |
    #!/bin/sh
    apk add --no-cache wget ca-certificates && update-ca-certificates
    wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /cloud_sql_proxy
    chmod +x /cloud_sql_proxy
    echo 8.8.8.8 >>/etc/resolv.conf
    echo "starting proxy in background"
    /cloud_sql_proxy -instances={{ .Values.database.instance }}=tcp:5432 -credential_file=/secrets/cloudsql/credentials.json &
    PROXY_PID=$!
    sleep 5

    python ./sql/create_readonly_user.py

    sleep 5

    echo "stopping proxy"
    kill $PROXY_PID

{{ else }}
  create_ro_user.sh: |
    #!/bin/sh

    python ./sql/create_readonly_user.py
{{- end -}}
