apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-internal
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "kernel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
