apiVersion: batch/v1beta1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Chart.Version }}
    heritage: {{ .Release.Service }}
spec:
  containers:
  - name: {{ .Chart.Name }}
    image:  "{{ .Values.provision.repository }}:{{ .Values.provision.tag | default .Chart.AppVersion }}"
    imagePullPolicy: {{ .Values.pullPolicy }}
    args:
      - {{ .Values.provisioner.command }}
    env:
    - name: PGHOST
      valueFrom :
        secretKeyRef:
          name: {{ .Values.provisioner.database.rootSecret }}
          key: host
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          name: {{ .Values.provisioner.database.rootSecret }}
          key: user
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Values.provisioner.database.rootSecret }}
          key: password
    - name: DB_NAME
      value: {{ .Values.provisioner.database.name }}
    - name: DB_USERNAME
      value: {{ .Values.provisioner.database.userName }}
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Values.provisioner.database.secret }}
          key: password
  restartPolicy: Never
  volumeMounts:
  - mountPath: /scripts
    name: {{ .Chart.Name }}
  {{ if .Values.provisioner.provider.gcp }}
  - mountPath: /secrets/cloudsql
    name: cloudsql-instance-credentials
    readOnly: true
  {{ end }}
  volumes:
  {{ if .Values.provider.gcp }}
  - name: cloudsql-instance-credentials
    secret:
      secretName: cloudsql-instance-credentials
  {{ end }}
