apiVersion: v1
kind: Service
metadata:
  name: {{ template "producer.fullname" . }}
  labels:
    app: {{ template "producer.name" . }}
    chart: {{ template "producer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ template "producer.name" . }}
    release: {{ .Release.Name }}
