apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Chart.Version }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.backup.schedule }}
  jobTemplate:
    spec:
      template:
        {{ if .Values.backup.kube2iam }}
        metadata:
          annotations:
            iam.amazonaws.com/role: {{ .Values.backup.AwsIamRoleArn }}
        {{ end }}
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image:  "{{ .Values.backup.repository }}:{{ .Values.backup.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.pullPolicy }}
            args:
              - {{ .Values.backup.command }}
            env:
            - name: BUCKET_NAME
              value: {{ .Values.backup.bucketName }}
            - name: COUCHDB_SERVICE_NAME
              value: {{ .Values.backup.couchdbServiceName }}
            {{ if .Values.backup.kms.enabled }}
            - name: AWS_KMS_KEY_ARN
              value: {{ .Values.backup.awsKmsKeyArn }}
            {{ end }}
            - name: AWS_REGION
              value: {{ .Values.backup.awsRegion }}
            - name: ENV
              value: {{ .Values.backup.env }}
            - name: PROJECT
              value: {{ .Values.backup.project }}
            - name: COUCHDB_USER
              valueFrom:
              secretKeyRef:
                name: {{ .Values.backup.couchdbSecret }}
                key: adminUsername
            - name: COUCHDB_PASSWORD
              valueFrom:
              secretKeyRef:
                name: {{ .Values.backup.couchdbSecret }}
                key: adminPassword
          restartPolicy: OnFailure
