apiVersion: v1
kind: ConfigMap
metadata:
  name: aether-add-tenant
data:
    add-tenant.sh: |
        #!/usr/bin/env bash
        #
        # Copyright (C) 2019 by eHealth Africa : http://www.eHealthAfrica.org
        #
        # See the NOTICE file distributed with this work for additional information
        # regarding copyright ownership.
        #
        # Licensed under the Apache License, Version 2.0 (the "License");
        # you may not use this file except in compliance with
        # the License.  You may obtain a copy of the License at
        #
        #   http://www.apache.org/licenses/LICENSE-2.0
        #
        # Unless required by applicable law or agreed to in writing,
        # software distributed under the License is distributed on an
        # "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
        # KIND, either express or implied.  See the License for the
        # specific language governing permissions and limitations
        # under the License.
        #
        set -Eeuo pipefail


        AUTH_RUN="/code/entrypoint.sh"

        # REQUIRES:
        # - DB running
        # - Kong running
        # - Keycloak running
        

        function create_tenant {
            REALM=$1
            DESC=${2:-$REALM}

            $AUTH_RUN add_realm \
                $REALM \
                "$DESC" \
                $LOGIN_THEME

            $AUTH_RUN add_public_client \
                $REALM \
                $KEYCLOAK_AETHER_CLIENT

            $AUTH_RUN add_oidc_client \
                $REALM \
                $KEYCLOAK_KONG_CLIENT

            $AUTH_RUN add_user \
                $REALM \
                $KEYCLOAK_INITIAL_USER_USERNAME \
                $KEYCLOAK_INITIAL_USER_PASSWORD

            $AUTH_RUN add_solution aether $REALM $KEYCLOAK_KONG_CLIENT

            # TODO Add when Kafka is ready

            # REQUIRES ( additionally ):
            # - Zookeeper running
            # - Kafka running

            # $AUTH_RUN add_kafka_tenant $REALM
        }


        echo "Creating tenant: {{ .Values.gw.env }}..."
        create_tenant  "{{ .Values.gw.env }}"  "{{ .Values.gw.env }} instance"
