apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-gather-service
data:
  gather.json: |
  {
    "name": "gather",
    "host": "http://{{ .Values.gw.aether.gather.internalService }}",
    "oidc_endpoints": [
      {
        "name": "protected",
        "url": "/",
        "strip_path": "false"
      }
    ],
    "public_endpoints": [
      {
        "name": "public",
        "url": "/-/gather/",
        "route_path": "/-/gather/",
        "strip_path": "true"
      }
    ]
  }
