apiVersion: v1
kind: ConfigMap
metadata:
  name: initialize
data:
  initialize.sh: |
    #!/usr/bin/env bash
    set -Eeuo pipefail

    # if no solutions indicated take ALL from the solution folder
    if [[ "${SOLUTIONS:-}" == "" ]]; then
      SOLUTIONS=""
      for file in /code/solution/*.json; do
        if [[ -f $file ]]; then
          _path=${file%.json}
          _solution=${_path##*/}
          SOLUTIONS="$SOLUTIONS $_solution"
        fi
      done
    fi

    echo " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo "  Adding realm  [$REALM]"
    echo "  to solutions  [${SOLUTIONS:-}]"
    echo " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

    gwm="/code/entrypoint.sh"
    $gwm add_app keycloak

    KONG_CLIENT=${KEYCLOAK_KONG_CLIENT:-kong}

    $gwm add_realm "$REALM" \
      description="Tenant: $REALM" \
      login_theme=${LOGIN_THEME:-keycloak} \
      account_theme=${ACCOUNT_THEME:-keycloak} \
      admin_theme=${ADMIN_THEME:-keycloak} \
      email_theme=${EMAIL_THEME:-keycloak}

    $gwm add_oidc_client "$REALM" "$KONG_CLIENT"

    # create realm manager
    $gwm add_admin "$REALM" "$INITIAL_SUPERUSER_USERNAME" "$INITIAL_SUPERUSER_PASSWORD"

    # create users manager
    $gwm add_user       "$REALM" "$INITIAL_ADMIN_USERNAME" "$INITIAL_ADMIN_PASSWORD"
    $gwm add_user_group "$REALM" "$INITIAL_ADMIN_USERNAME" "admin"

    # create simple user
    $gwm add_user       "$REALM" "$INITIAL_USER_USERNAME" "$INITIAL_USER_PASSWORD"
    $gwm add_user_group "$REALM" "$INITIAL_USER_USERNAME" "user"

    IFS=' ' read -a solutions <<< "$SOLUTIONS"
    for solution in "${solutions[@]}"; do
      $gwm remove_solution "$solution" "$REALM"
      $gwm add_solution    "$solution" "$REALM" "$KONG_CLIENT"

      # create public client for the aether solution
      if [[ $solution = "aether" ]]; then
        $gwm add_public_client "$REALM" "${KEYCLOAK_AETHER_CLIENT:-aether}"
      fi

      # create tenant in elasticsearch for Elasticsearch solution
      if [[ $solution = "elasticsearch" ]]; then
        $gwm add_elasticsearch_tenant "$REALM" 7
      fi

      # create tenant database for PlanFeld solution
      if [[ $solution = "planfeld" ]]; then
        service_creds=${INITIAL_ADMIN_USERNAME}:${INITIAL_ADMIN_PASSWORD}
        service_url=${BASE_HOST}/${REALM}/planfeld/api/v1/tenant/
        curl --silent --show-error --fail -u $service_creds -X POST ${service_url}
      fi
    done
