apiVersion: v1
kind: ConfigMap
metadata:
  name: aether-initialize
data:
  initialize.sh: |
    #!/usr/bin/env bash
    set -Eeuo pipefail
    gwm="/code/entrypoint.sh"
    $gwm add_app keycloak
    $gwm add_realm $REALM "Tenant: $REALM" $LOGIN_THEME
    $gwm add_public_client $REALM $KEYCLOAK_AETHER_CLIENT
    $gwm add_oidc_client $REALM $KEYCLOAK_KONG_CLIENT
    $gwm add_user $REALM $KEYCLOAK_INITIAL_USER_USERNAME $KEYCLOAK_INITIAL_USER_PASSWORD
    $gwm add_solution aether-gather $REALM $KEYCLOAK_KONG_CLIENT

    # Elasticsearch & Kibana
    $gwm add_service elasticsearch       "$1" $KEYCLOAK_KONG_CLIENT
    $gwm add_service kibana              "$1" $KEYCLOAK_KONG_CLIENT
    $gwm add_elasticsearch_tenant        "$1" 7