apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Chart.Version }}
    heritage: {{ .Release.Service }}
spec:
  containers:
  - name: {{ .Chart.Name }}
    image:  "{{ .Values.gw.repository }}:{{ .Values.gw.tag | default .Chart.Version }}"
    imagePullPolicy: {{ .Values.gw.pullPolicy }}
    args:
      - {{ .Values.gw.command }}
    env:
    - name: DEBUG
      value: null
    - name: KEYCLOAK_GLOBAL_ADMIN
      value: {{ .Values.gw.keyCloak.globalAdmin }}
    - name: KEYCLOAK_GLOBAL_PASSWORD
      value: {{ .Values.gw.keyCloak.globalPassword }}
    - name: KEYCLOAK_KONG_CLIENT
      value: {{ .Values.gw.keyCloak.kongClient }}
    - name: BASE_DOMAIN
      value: {{ .Values.gw.baseDomain }}
    - name: BASE_HOST
      value: {{ .Values.gw.baseHost }}
    - name: KEYCLOAK_INTERNAL
      value: {{ .Values.gw.keyCloak.internalService }}
    - name: KONG_INTERNAL
      value: {{ .Values.gw.kong.internalService }}
    restartPolicy: Never
