apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Chart.Version }}
    heritage: {{ .Release.Service }}
spec:
  containers:
  - name: {{ .Chart.Name }}
    image:  "{{ .Values.gw.repository }}:{{ .Values.gw.tag | default .Chart.Version }}"
    imagePullPolicy: {{ .Values.gw.pullPolicy }}
    args:
      - {{ .Values.gw.command }}
    env:
    - name: DEBUG
      value: {{ .Values.gw.debug }}
    - name: KEYCLOAK_GLOBAL_ADMIN
      value: {{ .Values.gw.keyCloak.globalAdmin }}
    - name: KEYCLOAK_GLOBAL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Values.gw.keyCloak.secret.name }}
          key: {{ .Values.gw.keyCloak.secret.globalPasswordKey }}
    - name: KEYCLOAK_KONG_CLIENT
      value: {{ .Values.gw.keyCloak.kongClient }}
    - name: BASE_DOMAIN
      value: {{ .Values.gw.baseDomain }}
    - name: BASE_HOST
      value: {{ .Values.gw.baseHost }}
    - name: KEYCLOAK_INTERNAL
      value: {{ .Values.gw.keyCloak.internalService }}
    - name: KONG_INTERNAL
      value: {{ .Values.gw.kong.internalService }}
    volumeMounts:
    {{- range $key, $value := .Values.gw.aether.services }}
    - name: {{ $value }}
      mountPath: /code/service/
    {{ end }}
    - name: aether-solution
      mountPath: /code/solution/
  volumes:
  {{- range $key, $value := .Values.gw.aether.services }}
  - name: {{ $value }}-service
    configMap:
      name: {{ $value }}-service
  {{ end }}
