apiVersion: v1
kind: ConfigMap
metadata:
  name: kernel-service
data:
  kernel.json: |
    {
      "name": "kernel",
      "host": "http://{{ .Values.gw.aether.kernel.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "url": "/",
          "strip_path": "false"
        }
      ],
      "public_endpoints": [
        {
          "name": "public",
          "url": "/-/kernel/",
          "route_path": "/-/kernel/",
          "strip_path": "true"
        }
      ]
    }
