apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-odk-service
data:
  ui.json: |
    {
      "name": "odk",
      "host": "http://{{ .Values.gw.aether.odk.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "url": "/",
          "strip_path": "false"
        }
      ],
      "public_endpoints": [
        {
          "name": "public",
          "url": "/-/odk/",
          "route_path": "/-/odk/",
          "strip_path": "true"
        }
      ]
    }
