apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Chart.Version }}
    heritage: {{ .Release.Service }}
spec:
  containers:
  - name: {{ .Chart.Name }}
    image:  "{{ .Values.gw.repository }}:{{ .Values.gw.tag | default .Chart.Version }}"
    imagePullPolicy: {{ .Values.gw.pullPolicy }}
    command: ["{{ .Values.gw.command }}"]
    args: ["{{ .Values.gw.args }}"]
    env:
    - name: DEBUG
      value: "{{ .Values.gw.debug }}"

    - name: BASE_DOMAIN
      value: {{ .Values.gw.baseDomain }}
    - name: BASE_HOST
      value: {{ .Values.gw.baseHost }}

    - name: KEYCLOAK_INTERNAL
      value: {{ .Values.gw.keycloak.internalService }}
    - name: KEYCLOAK_MASTER_REALM
      value: {{ .Values.gw.keycloak.masterRealm }}
    - name: KEYCLOAK_GLOBAL_ADMIN
      value: {{ .Values.gw.keycloak.globalAdmin }}
    - name: KEYCLOAK_GLOBAL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Values.gw.keycloak.secret.name }}
          key: {{ .Values.gw.keycloak.secret.passwordKey }}

    - name: KONG_INTERNAL
      value: {{ .Values.gw.kong.internalService }}

    - name: ELASTICSEARCH_HOST
      value: {{ .Values.gw.elasticsearch.internalService }}
    - name: ELASTICSEARCH_USER
      value: {{ .Values.gw.elasticsearch.user }}
    - name: ELASTICSEARCH_PW
      valueFrom:
        secretKeyRef:
          name: {{ .Values.gw.elasticsearch.secret.name }}
          key: {{ .Values.gw.elasticsearch.secret.passwordKey }}

    # Used by "initialize.sh" script
    - name: SOLUTIONS
      value: {{ .Values.gw.init.solutions }}

    - name: LOGIN_THEME
      value: {{ .Values.gw.init.loginTheme }}
    - name: ACCOUNT_THEME
      value: {{ .Values.gw.init.accountTheme }}
    - name: ADMIN_THEME
      value: {{ .Values.gw.init.adminTheme }}
    - name: EMAIL_THEME
      value: {{ .Values.gw.init.emailTheme }}

    - name: KEYCLOAK_PUBLIC_CLIENT
      value: {{ .Values.gw.init.publicClient }}
    - name: KEYCLOAK_KONG_CLIENT
      value: {{ .Values.gw.init.kongClient }}

    - name: INITIAL_SUPERUSER_USERNAME
      value: {{ .Values.gw.init.initialSU }}
    - name: INITIAL_SUPERUSER_PASSWORD
      value: {{.Values.gw.init.initialSUPassword}}

    - name: INITIAL_ADMIN_USERNAME
      value: {{ .Values.gw.init.initialAdmin }}
    - name: INITIAL_ADMIN_PASSWORD
      value: {{.Values.gw.init.initialAdminPassword}}

    - name: INITIAL_USER_USERNAME
      value: {{ .Values.gw.init.initialUser }}
    - name: INITIAL_USER_PASSWORD
      value: {{.Values.gw.init.initialUserPassword}}

    volumeMounts:
    - name: services
      mountPath: /code/service
    - name: solutions
      mountPath: /code/solution
    - name: apps
      mountPath: /code/app
    - name: initialize
      mountPath: /code/scripts

  volumes:
  - name: services
    configMap:
      name: services
  - name: apps
    configMap:
      name: apps
  - name: solutions
    configMap:
      name: solutions
  - name: initialize
    configMap:
      name: initialize
      defaultMode: 0755
