apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Chart.Version }}
    heritage: {{ .Release.Service }}
spec:
  containers:
  - name: {{ .Chart.Name }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
    imagePullPolicy: {{ .Values.app.pullPolicy }}
    command: ["{{ .Values.app.command }}"]
    args: ["{{ .Values.app.args }}"]
    env:
    - name: DEBUG
      value: "{{ .Values.app.debug }}"

    - name: BASE_DOMAIN
      value: {{ .Values.app.baseDomain }}
    - name: BASE_HOST
      value: {{ .Values.app.baseHost }}

    - name: KEYCLOAK_INTERNAL
      value: {{ .Values.app.keycloak.internalService }}
    - name: KEYCLOAK_MASTER_REALM
      value: {{ .Values.app.keycloak.masterRealm }}
    - name: KEYCLOAK_GLOBAL_ADMIN
      value: {{ .Values.app.keycloak.globalAdmin }}
    - name: KEYCLOAK_GLOBAL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Values.app.keycloak.secret.name }}
          key: {{ .Values.app.keycloak.secret.passwordKey }}

    - name: KONG_INTERNAL
      value: {{ .Values.app.kong.internalService }}

    - name: ELASTICSEARCH_HOST
      value: {{ .Values.app.elasticsearch.internalService }}
    - name: ELASTICSEARCH_USER
      value: {{ .Values.app.elasticsearch.user }}
    - name: ELASTICSEARCH_PW
      valueFrom:
        secretKeyRef:
          name: {{ .Values.app.elasticsearch.secret.name }}
          key: {{ .Values.app.elasticsearch.secret.passwordKey }}

    - name: WEB_SERVICE_NAME
      value: {{ .Values.app.gateway.name }}
    - name: WEB_SERVER_PORT
      value: {{ quote .Values.app.gateway.port }}

    # Used by "initialize.sh" script
    - name: SOLUTIONS
      value: {{ .Values.app.init.solutions }}

    - name: LOGIN_THEME
      value: {{ .Values.app.init.loginTheme }}
    - name: ACCOUNT_THEME
      value: {{ .Values.app.init.accountTheme }}
    - name: ADMIN_THEME
      value: {{ .Values.app.init.adminTheme }}
    - name: EMAIL_THEME
      value: {{ .Values.app.init.emailTheme }}

    - name: KEYCLOAK_PUBLIC_CLIENT
      value: {{ .Values.app.init.publicClient }}
    - name: KEYCLOAK_KONG_CLIENT
      value: {{ .Values.app.init.kongClient }}

    - name: INITIAL_SUPERUSER_USERNAME
      value: {{ .Values.app.init.initialSU }}
    - name: INITIAL_SUPERUSER_PASSWORD
      value: {{ .Values.app.init.initialSUPassword }}

    - name: INITIAL_ADMIN_USERNAME
      value: {{ .Values.app.init.initialAdmin }}
    - name: INITIAL_ADMIN_PASSWORD
      value: {{ .Values.app.init.initialAdminPassword }}

    - name: INITIAL_USER_USERNAME
      value: {{ .Values.app.init.initialUser }}
    - name: INITIAL_USER_PASSWORD
      value: {{ .Values.app.init.initialUserPassword }}

    volumeMounts:
    - name: services
      mountPath: /code/service
    - name: solutions
      mountPath: /code/solution
    - name: apps
      mountPath: /code/app
    - name: initialize
      mountPath: /code/scripts
    - name: data
      mountPath: /code/data

  volumes:
  - name: services
    configMap:
      name: services
  - name: apps
    configMap:
      name: apps
  - name: solutions
    configMap:
      name: solutions
  - name: initialize
    configMap:
      name: initialize
      defaultMode: 0755
  - name: data
    configMap:
      name: data
