apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Chart.Version }}
    heritage: {{ .Release.Service }}
spec:
  containers:
  - name: {{ .Chart.Name }}
    image:  "{{ .Values.gw.repository }}:{{ .Values.gw.tag | default .Chart.Version }}"
    imagePullPolicy: {{ .Values.gw.pullPolicy }}
    command: ["{{ .Values.gw.command }}"]
    args: ["{{ .Values.gw.args }}"]
    env:
    - name: DEBUG
      value: "{{ .Values.gw.debug }}"
    - name: KEYCLOAK_GLOBAL_ADMIN
      value: {{ .Values.gw.keyCloak.globalAdmin }}
    - name: KEYCLOAK_GLOBAL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Values.gw.keyCloak.secret.name }}
          key: {{ .Values.gw.keyCloak.secret.passwordKey }}
    - name: LOGIN_THEME
      value: {{ .Values.gw.logingTheme }}
    - name: KEYCLOAK_AETHER_CLIENT
      value: {{ .Values.gw.keyCloak.aetherClient }}
    - name: KEYCLOAK_KONG_CLIENT
      value: {{ .Values.gw.keyCloak.kongClient }}
    - name: BASE_DOMAIN
      value: {{ .Values.gw.baseDomain }}
    - name: BASE_HOST
      value: {{ .Values.gw.baseHost }}
    - name: KEYCLOAK_INTERNAL
      value: {{ .Values.gw.keyCloak.internalService }}
    - name: KEYCLOAK_HOST
      value: {{ .Values.gw.keyCloak.host }}
    - name: KEYCLOAK_INITIAL_USER_USERNAME
      value: {{ .Values.gw.keyCloak.initial_user }}
    - name: KEYCLOAK_INITIAL_USER_PASSWORD
      value: {{.Values.gw.keyCloak.initial_password}}
    - name: KONG_INTERNAL
      value: {{ .Values.gw.kong.internalService }}
    - name: REALM
      value: {{ .Values.gw.keyCloak.realm }}
    - name: ELASTICSEARCH_HOST
      value: {{ .Values.gw.elasticsearch.internalService }}
    - name: ELASTICSEARCH_USER  
      value: {{ .Values.gw.elasticsearch.user }}      
    - name: ELASTICSEARCH_PW
      valueFrom:
        secretKeyRef:
          name: {{ .Values.gw.elasticsearch.secret.name }}
          key: {{ .Values.gw.elasticsearch.secret.passwordKey }}
    volumeMounts:
    - name: aether-services
      mountPath: /code/service
    - name: aether-gather-solution
      mountPath: /code/solution
    - name: aether-apps
      mountPath: /code/app
    - name: aether-initialize
      mountPath: /code/scripts
  volumes:
  - name: aether-services
    configMap:
      name: aether-services
  - name: aether-apps
    configMap:
      name: aether-apps
  - name: aether-gather-solution
    configMap:
      name: aether-gather-solution
  - name: aether-initialize
    configMap:
      name: aether-initialize
      defaultMode: 0755
