apiVersion: v1
kind: ConfigMap
metadata:
  name: aether-services
data:
  gather.json: |
    {
      "name": "gather",
      "host": "http://gather",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": [
            "/{realm}/{name}/"
          ]
        }
      ],
      "public_endpoints": [
        {
          "name": "public",
          "paths": [
            "/{public_realm}/{name}/"
          ]
        }
      ]
    }

  odk.json: |
    {
      "name": "odk",
      "host": "http://aether-odk",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": [
            "/{realm}/{name}/"
          ]
        }
      ],
      "public_endpoints": [
        {
          "name": "public",
          "paths": [
            "/{public_realm}/{name}/",
            "/{realm}/{name}/formList",
            "/{realm}/{name}/forms",
            "/{realm}/{name}/media-file/",
            "/{realm}/{name}/submission"
          ]
        }
      ]
    }

  ui.json: |
    {
      "name": "ui",
      "host": "http://aether-ui",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": [
            "/{realm}/{name}/"
          ]
        }
      ],
      "public_endpoints": [
        {
          "name": "public",
          "paths": [
            "/{public_realm}/{name}/"
          ]
        }
      ]
    }
 
  kernel.json: |
    {
      "name": "kernel",
      "host": "http://aether-kernel",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": [
            "/{realm}/{name}/"
          ]
        }
      ],
      "public_endpoints": [
        {
          "name": "public",
          "paths": [
            "/{public_realm}/{name}/"
          ]
        }
      ]
    }     

