apiVersion: v1
kind: ConfigMap
metadata:
  name: services
data:
  gather.json: |
    {
      "name": "gather",
      "host": "http://gather",
      "paths": ["/{public_realm}/{name}"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"]
        }
      ]
    }
  aether-odk.json: |
    {
      "name": "odk",
      "host": "http://aether-odk",
      "paths": ["/{public_realm}/{name}"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"]
        }
      ],
      "public_endpoints": [
        {
          "name": "public",
          "paths": [
            "/{realm}/{name}/formList",
            "/{realm}/{name}/forms",
            "/{realm}/{name}/media-file/",
            "/{realm}/{name}/submission"
          ]
        }
      ]
    }
  aether-kernel-ui.json: |
    {
      "name": "ui",
      "host": "http://aether-ui",
      "paths": ["/{public_realm}/{name}"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"]
        }
      ]
    }
  aether-kernel.json: |
    {
      "name": "kernel",
      "host": "http://aether-kernel",
      "paths": ["/{public_realm}/{name}"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"]
        }
      ]
    }
  planfeld-analytics.json: |
    {
      "name": "analytics",
      "host": "http://planfeld-analytics",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"],
          "strip_path": "true"
        }
      ]
    }
  planfeld-monitor.json: |
    {
      "name": "monitor",
      "host": "http://planfeld-monitor",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"],
          "strip_path": "true"
        }
      ]
    }
  planfeld-planner.json: |
    {
      "name": "planner",
      "host": "http://planfeld-planner",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"],
          "strip_path": "true"
        }
      ]
    }
  planfeld-ui.json: |
    {
      "name": "ui",
      "host": "http://planfeld-ui",
      "paths": ["/static/"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}"],
          "oidc_override": {
            "config.app_login_redirect_url": "${host}/${realm}/"
          }
        }
      ]
    }