apiVersion: v1
kind: ConfigMap
metadata:
  name: services
data:
  # Aether + Gather
  kernel.json: |
    {
      "name": "kernel",
      "host": "{{ .Values.gw.aether.kernel.internalService }}",
      "paths": ["/{public_realm}/{name}$", "/{public_realm}/{name}/"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"]
        }
      ]
    }
  kernel-ui.json: |
    {
      "name": "kernel-ui",
      "host": "{{ .Values.gw.aether.ui.internalService }}",
      "paths": ["/{public_realm}/{name}$", "/{public_realm}/{name}/"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"]
        }
      ]
    }
  odk.json: |
    {
      "name": "odk",
      "host": "{{ .Values.gw.aether.odk.internalService }}",
      "paths": ["/{public_realm}/{name}$", "/{public_realm}/{name}/"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"]
        }
      ],
      "public_endpoints": [
        {
          "name": "public",
          "paths": [
            "/{realm}/{name}/formList",
            "/{realm}/{name}/forms",
            "/{realm}/{name}/media-file/",
            "/{realm}/{name}/submission"
          ]
        }
      ]
    }
  producer.json: |
    {
      "name": "producer",
      "host": "{{ .Values.gw.aether.producer.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  gather.json: |
    {
      "name": "gather",
      "host": "{{ .Values.gw.gather.internalService }}",
      "host": "http://gather",
      "paths": ["/{public_realm}/{name}$", "/{public_realm}/{name}/"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"]
        }
      ]
    }

  # Aether consumers
  ckan-consumer.json: |
    {
      "name": "ckan-consumer",
      "host": "{{ .Values.gw.consumers.ckan.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  es-consumer.json: |
    {
      "name": "es-consumer",
      "host": "{{ .Values.gw.consumers.elasticsearch.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"]
        }
      ]
    }
  firebase-consumer.json: |
    {
      "name": "firebase-consumer",
      "host": "{{ .Values.gw.consumers.firebase.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"]
        }
      ]
    }
  stream-consumer.json: |
    {
      "name": "stream-consumer",
      "host": "{{ .Values.gw.consumers.stream.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }

  # Elasticsearch & Kibana
  elasticsearch.json: |
    {
      "name": "elasticsearch",
      "host": "{{ .Values.gw.elasticsearch.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  kibana.json: |
    {
      "name": "kibana",
      "host": "{{ .Values.gw.kibana.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }

  # PlanFeld
  planfeld.json: |
    {
      "name": "planfeld",
      "host": "{{ .Values.gw.planfeld.planfeld.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  planfeld-health.json: |
    {
      "name": "planfeld-health",
      "host": "{{ .Values.gw.planfeld.planfeld.internalService }}/health",
      "paths": ["/{public_realm}/planfeld/health"],
      "strip_path": "true",
      "public_endpoints": [
        {
          "name": "public",
          "paths": ["/{realm}/planfeld/health"],
          "strip_path": "true"
        }
      ]
    }
  monitor.json: |
    {
      "name": "monitor",
      "host": "{{ .Values.gw.planfeld.monitor.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  monitor-health.json: |
    {
      "name": "monitor-health",
      "host": "{{ .Values.gw.planfeld.monitor.internalService }}/health",
      "paths": ["/{public_realm}/monitor/health"],
      "strip_path": "true",
      "public_endpoints": [
        {
          "name": "public",
          "paths": ["/{realm}/monitor/health"],
          "strip_path": "true"
        }
      ]
    }
  planner.json: |
    {
      "name": "planner",
      "host": "{{ .Values.gw.planfeld.planner.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  planner-health.json: |
    {
      "name": "planner-health",
      "host": "{{ .Values.gw.planfeld.planner.internalService }}/health",
      "paths": ["/{public_realm}/planner/health"],
      "strip_path": "true",
      "public_endpoints": [
        {
          "name": "public",
          "paths": ["/{realm}/planner/health"],
          "strip_path": "true"
        }
      ]
    }
  ui.json: |
    {
      "name": "ui",
      "host": "{{ .Values.gw.planfeld.ui.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  ui-health.json: |
    {
      "name": "ui-health",
      "host": "{{ .Values.gw.planfeld.ui.internalService }}/health",
      "paths": ["/{public_realm}/ui/health"],
      "strip_path": "true",
      "public_endpoints": [
        {
          "name": "public",
          "paths": ["/{realm}/ui/health"],
          "strip_path": "true"
        }
      ]
    }
  ui-static.json: |
    {
      "name": "ui-static",
      "host": "{{ .Values.gw.planfeld.ui.internalService }}/static",
      "paths": ["/{public_realm}/ui/static", "/static"],
      "strip_path": "true"
    }
