apiVersion: v1
kind: ConfigMap
metadata:
  name: services
data:
  gather.json: |
    {
      "name": "gather",
      "host": "http://gather",
      "paths": ["/{public_realm}/{name}"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"]
        }
      ]
    }
  elasticsearch.json: |
    {
      "name": "elasticsearch",
      "host": "{{ .Values.gw.elasticsearch.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": [
            "/{realm}/{name}"
          ],
          "strip_path": "true",
          "oidc_override": {
            "config.user_keys": [
              "preferred_username",
              "email",
              "groups"
            ]
          }
        }
      ]
    }
  kibana.json: |
    {
      "name": "kibana",
      "host": "{{ .Values.gw.kibana.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": [
            "/{realm}/{name}"
          ],
          "strip_path": "true",
          "oidc_override": {
            "config.user_keys": [
              "preferred_username",
              "email",
              "groups"
            ]
          }
        }
      ]
    }
  odk.json: |
    {
      "name": "odk",
      "host": "http://aether-odk",
      "paths": ["/{public_realm}/{name}"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"]
        }
      ],
      "public_endpoints": [
        {
          "name": "public",
          "paths": [
            "/{realm}/{name}/formList",
            "/{realm}/{name}/forms",
            "/{realm}/{name}/media-file/",
            "/{realm}/{name}/submission"
          ]
        }
      ]
    }
  kernel-ui.json: |
    {
      "name": "ui",
      "host": "http://aether-ui",
      "paths": ["/{public_realm}/{name}"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"]
        }
      ]
    }
  kernel.json: |
    {
      "name": "kernel",
      "host": "http://aether-kernel",
      "paths": ["/{public_realm}/{name}"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"]
        }
      ]
    }
  analytics.json: |
    {
      "name": "analytics",
      "host": "http://planfeld-analytics:3001",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"],
          "strip_path": "true"
        }
      ]
    }
  monitor.json: |
    {
      "name": "monitor",
      "host": "http://planfeld-monitor:3002",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"],
          "strip_path": "true"
        }
      ]
    }
  planner.json: |
    {
      "name": "planner",
      "host": "http://planfeld-planner:3003",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"],
          "strip_path": "true"
        }
      ]
    }
  planfeld.json: |
    {
      "name": "planfeld",
      "host": "http://planfeld-ui:3000",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}"],
          "oidc_override": {
            "config.app_login_redirect_url": "${host}/${realm}/${name}"
          }
        }
      ]
    }