apiVersion: v1
kind: ConfigMap
metadata:
  name: services
data:
  # Gateway Landing page
  gateway.json: |
    {
      "name": "{{ .Values.app.gateway.name }}",
      "host": "{{ .Values.app.gateway.internalService }}",
      "paths": [
        "/{public_realm}/{name}/health$",
        "/{public_realm}/{name}/static"
      ],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": [
            "/{realm}$",
            "/{realm}/$",
            "/{realm}/{name}/",
            "/{realm}/oauth2/"
          ]
        }
      ],
      "public_endpoints": [
        {
          "name": "public",
          "paths": [
            "/{realm}/{name}/health$",
            "/{realm}/{name}/static"
          ]
        }
      ]
    }

  # Aether + Gather
  kernel.json: |
    {
      "name": "kernel",
      "host": "{{ .Values.app.aether.kernel.internalService }}",
      "paths": ["/{public_realm}/{name}$", "/{public_realm}/{name}/"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"]
        }
      ]
    }
  kernel-ui.json: |
    {
      "name": "kernel-ui",
      "host": "{{ .Values.app.aether.ui.internalService }}",
      "paths": ["/{public_realm}/{name}$", "/{public_realm}/{name}/"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"]
        }
      ]
    }
  odk.json: |
    {
      "name": "odk",
      "host": "{{ .Values.app.aether.odk.internalService }}",
      "paths": ["/{public_realm}/{name}$", "/{public_realm}/{name}/"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"]
        }
      ],
      "public_endpoints": [
        {
          "name": "public",
          "paths": [
            "/{realm}/{name}/formList",
            "/{realm}/{name}/forms",
            "/{realm}/{name}/media-file/",
            "/{realm}/{name}/submission"
          ]
        }
      ]
    }
  producer.json: |
    {
      "name": "producer",
      "host": "{{ .Values.app.aether.producer.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  gather.json: |
    {
      "name": "gather",
      "host": "{{ .Values.app.gather.internalService }}",
      "host": "http://gather",
      "paths": ["/{public_realm}/{name}$", "/{public_realm}/{name}/"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"]
        }
      ]
    }

  # Aether consumers
  ckan-consumer.json: |
    {
      "name": "ckan-consumer",
      "host": "{{ .Values.app.consumers.ckan.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  es-consumer.json: |
    {
      "name": "es-consumer",
      "host": "{{ .Values.app.consumers.elasticsearch.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  firebase-consumer.json: |
    {
      "name": "firebase-consumer",
      "host": "{{ .Values.app.consumers.firebase.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  stream-consumer.json: |
    {
      "name": "stream-consumer",
      "host": "{{ .Values.app.consumers.stream.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }

  # Elasticsearch & Kibana
  elasticsearch.json: |
    {
      "name": "elasticsearch",
      "host": "{{ .Values.app.elasticsearch.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true",
          "oidc_override": {
            "config.user_keys": [
              "preferred_username",
              "email",
              "groups"
            ]
          }
        }
      ]
    }
  kibana.json: |
    {
      "name": "kibana",
      "host": "{{ .Values.app.kibana.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true",
          "oidc_override": {
            "config.user_keys": [
              "preferred_username",
              "email",
              "groups"
            ]
          }
        }
      ]
    }

  # PlanFeld
  planfeld.json: |
    {
      "name": "planfeld",
      "host": "{{ .Values.app.planfeld.planfeld.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  planfeld-health.json: |
    {
      "name": "planfeld-health",
      "host": "{{ .Values.app.planfeld.planfeld.internalService }}/health",
      "paths": ["/{public_realm}/planfeld/health"],
      "strip_path": "true",
      "public_endpoints": [
        {
          "name": "public",
          "paths": ["/{realm}/planfeld/health"],
          "strip_path": "true"
        }
      ]
    }
  monitor.json: |
    {
      "name": "monitor",
      "host": "{{ .Values.app.planfeld.monitor.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  monitor-health.json: |
    {
      "name": "monitor-health",
      "host": "{{ .Values.app.planfeld.monitor.internalService }}/health",
      "paths": ["/{public_realm}/monitor/health"],
      "strip_path": "true",
      "public_endpoints": [
        {
          "name": "public",
          "paths": ["/{realm}/monitor/health"],
          "strip_path": "true"
        }
      ]
    }
  planner.json: |
    {
      "name": "planner",
      "host": "{{ .Values.app.planfeld.planner.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  planner-health.json: |
    {
      "name": "planner-health",
      "host": "{{ .Values.app.planfeld.planner.internalService }}/health",
      "paths": ["/{public_realm}/planner/health"],
      "strip_path": "true",
      "public_endpoints": [
        {
          "name": "public",
          "paths": ["/{realm}/planner/health"],
          "strip_path": "true"
        }
      ]
    }
  ui.json: |
    {
      "name": "ui",
      "host": "{{ .Values.app.planfeld.ui.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}$", "/{realm}/{name}/"],
          "strip_path": "true"
        }
      ]
    }
  ui-health.json: |
    {
      "name": "ui-health",
      "host": "{{ .Values.app.planfeld.ui.internalService }}/health",
      "paths": ["/{public_realm}/ui/health"],
      "strip_path": "true",
      "public_endpoints": [
        {
          "name": "public",
          "paths": ["/{realm}/ui/health"],
          "strip_path": "true"
        }
      ]
    }
  ui-static.json: |
    {
      "name": "ui-static",
      "host": "{{ .Values.app.planfeld.ui.internalService }}/static",
      "paths": ["/{public_realm}/ui/static", "/static"],
      "strip_path": "true"
    }
