apiVersion: v1
kind: ConfigMap
metadata:
  name: services
data:
  gather.json: |
    {
      "name": "gather",
      "host": "http://gather",
      "paths": ["/{public_realm}/{name}"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"]
        }
      ]
    }

  elasticsearch.json: |
    {
      "name": "elasticsearch",
      "host": "{{ .Values.gw.elasticsearch.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": [
            "/{realm}/{name}"
          ],
          "strip_path": "true",
          "oidc_override": {
            "config.user_keys": [
              "preferred_username",
              "email",
              "groups"
            ]
          }
        }
      ]
    }

  es-consumer.json: |
    {
      "name": "es-consumer",
      "host": "{{ .Values.gw.aetherElasticsearchConsumer.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": [
            "/{realm}/{name}"
          ],
          "strip_path": "true",
          "oidc_override": {
            "config.user_keys": [
              "preferred_username",
              "email",
              "groups"
            ]
          }
        }
      ]
    }

  kibana.json: |
    {
      "name": "kibana",
      "host": "{{ .Values.gw.kibana.internalService }}",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": [
            "/{realm}/{name}"
          ],
          "strip_path": "true",
          "oidc_override": {
            "config.user_keys": [
              "preferred_username",
              "email",
              "groups"
            ]
          }
        }
      ]
    }

  odk.json: |
    {
      "name": "odk",
      "host": "http://aether-odk",
      "paths": ["/{public_realm}/{name}"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"]
        }
      ],
      "public_endpoints": [
        {
          "name": "public",
          "paths": [
            "/{realm}/{name}/formList",
            "/{realm}/{name}/forms",
            "/{realm}/{name}/media-file/",
            "/{realm}/{name}/submission"
          ]
        }
      ]
    }
  kernel-ui.json: |
    {
      "name": "kernel-ui",
      "host": "http://aether-ui",
      "paths": ["/{public_realm}/{name}"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"]
        }
      ]
    }
  kernel.json: |
    {
      "name": "kernel",
      "host": "http://aether-kernel",
      "paths": ["/{public_realm}/{name}"],
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"]
        }
      ]
    }

  planner.json: |
    {
      "name": "planner",
      "host": "http://planfeld-planner",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"],
          "strip_path": "true"
        }
      ]
    }
  monitor.json: |
    {
      "name": "monitor",
      "host": "http://planfeld-monitor",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"],
          "strip_path": "true"
        }
      ]
    }
  ui.json: |
    {
      "name": "ui",
      "host": "http://planfeld-ui",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"],
          "strip_path": "true"
        }
      ]
    }
  ui-static.json: |
    {
      "name": "planfeld-static",
      "host": "http://planfeld-ui/static",
      "paths": ["/-/planfeld/static", "/static"],
      "strip_path": "true"
    }
  analytics.json: |
    {
      "name": "analytics",
      "host": "http://planfeld-analytics",
      "oidc_endpoints": [
        {
          "name": "protected",
          "paths": ["/{realm}/{name}"],
          "strip_path": "true"
        }
      ]
    }