apiVersion: v1
kind: ConfigMap
metadata:
  name: aether-gather-solution
data:
  aether-gather.json: |
    {
      "services": ["kernel", "ui", "gather", "odk"]
    }
  planfeld.json: |
    {
      "services": [ "analytics", "monitor", "planner", "ui" ]
    }