apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-aether-solution
data:
  aether_service.json: |
    {
      "name": "aether",
      "services": [
        "odk", "ui", "gather", "kernel"
      ]
    }
