apiVersion: v1
kind: ConfigMap
metadata:
  name: solutions
data:
  aether-gather.json: |
    {
      "name": "aether-gather",
      "services": [
        "kernel",
        "kernel-ui",
        "gather",
        "odk",
        "es-consumer",
        "firebase-consumer",
        "ckan-consumer"]
    }
  planfeld.json: |
    {
      "name": "planfeld",
      "services": [
        "monitor", "monitor-health",
        "planfeld", "planfeld-health",
        "planner", "planner-health",
        "ui", "ui-static"
      ]
    }
