{{ if .Values.app.config.enabled }}
{{- range $config := .Values.app.config.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic.fullname" $ }}-{{ $config.name  | replace "." "-" }}
data:
  {{ $config.name }}: |
{{ $config.data | indent 4 }}
---
{{- end -}}
{{ end }}