{{ if .Values.app.db.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "generic.fullname" . }}-init-pg-config
data:
  init.sh: |
    #!/bin/bash
    set -e
    apk add --no-cache ca-certificates && update-ca-certificates
    wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /cloud_sql_proxy
    chmod +x /cloud_sql_proxy
    echo 8.8.8.8 >>/etc/resolv.conf
    echo "starting proxy in background"
    /cloud_sql_proxy -instances={{ .Values.database.instance }}=tcp:5432 -credential_file=/secrets/cloudsql/credentials.json &
    PROXY_PID=$!
    sleep 5

    # check to see if database exists
    database="select count(*) from pg_catalog.pg_database where datname = '$DB_NAME'"
    cmd="psql -t -c \"$database\""
    db_exists=`eval $cmd`

    if [ $db_exists -eq 0 ]; then
        psql -c "CREATE DATABASE $DB_NAME;"
        psql -c "CREATE USER IF NOT EXISTS $DB_USERNAME WITH PASSWORD '$DB_PASSWORD';"
        psql -c "ALTER DATABASE $DB_NAME OWNER TO $DB_USERNAME;"
        psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USERNAME;"
        psql -c "ALTER DATABASE $DB_NAME OWNER TO $DB_USERNAME;"
        echo "sql executed.."
    fi

    # create database extensions
    {{ if .Values.app.db.extensions }}
    {{- range .Values.app.db.extensions }}
    echo "creating Postgres database extensions"
    psql -d $DB_NAME -c 'CREATE EXTENSION IF NOT EXISTS {{ . | quote }} ;'
    {{- end }}
    {{ end }}

    sleep 5
    echo "stopping proxy"
    kill $PROXY_PID
{{ end }}
