{{- if and .Values.kibana.ingress.enabled .Values.kibana.enabled }}
{{- $serviceName:= printf "%s-%s"  (include "opendistro-es.fullname" .) "kibana-svc" }}
{{- $servicePort := .Values.kibana.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
  name: {{ template "opendistro-es.fullname" . }}-kibana
  annotations:
    {{- range $key, $value := .Values.kibana.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range .Values.kibana.ingress.hosts }}
      {{- $url := splitList "/" . }}
    - host: {{ first $url }}
      http:
        paths:
          - path: /{{ rest $url | join "/" }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.kibana.ingress.tls }}
  tls:
{{ toYaml .Values.kibana.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}

