# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "opendistro-es.fullname" . }}-kibana-config
data:
  kibana.yml: {{ toYaml .Values.kibana.config | quote }}  

