{{- if and .Values.global.rbac.enabled .Values.kibana.enabled }}
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1beta1"}}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
{{- end }}
kind: Role
metadata:
  name: {{ template "opendistro-es.kibana.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "opendistro-es.fullname" . }}-psp
{{- end }}
