# Default values for producer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
application:
  command: start
  config: /etc/producer/config.json
image:
  repository: ehealthafrica/aether-producer
  tag: 0.9.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9005
kernel_url: http://kernel
kernel_admin_username: admin
ingress:
  enabled: false
