apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  {{ if .Values.podAntiAffinity.enabled }}
  {{- include "aether-kernel.podAntiAffinity" . | indent 2 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      {{- include "aether-kernel-ui.initContainers" . | indent 6 }}
        volumeMounts:
        - mountPath: /scripts
          name: init-config
        {{ if .Values.provider.gcp }}
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        {{ end }}
      containers:
        {{- include "aether-kernel.extraContainers" . | indent 6 }}
        - name: ui
          # This default allows us to overwrite ' .Chart.Version' through the command line
          image: "{{ .Values.app.repository }}:{{ .Values.app.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          args:
          - {{ .Values.app.command }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          {{- include "aether-kernel-ui.probes" . | indent 8 }}
          env:
          {{- include "aether-kernel-ui.extraContainers" . | indent 8 }}
          volumeMounts:
          - mountPath: /var/www/static
            name: static-assets-volume
          {{ if .Values.imagePullSecrets.enabled }}
          imagePullSecrets:
            - name: {{ .Values.imagePullSecrets.name }}
          {{ end }}
      volumes:
      - name: {{ .Chart.Name }}
      - name: static-assets-volume
      - name: nginx-config
        configMap:
          name: {{ .Chart.Name }}-nginx-config
      - name: init-config
        configMap:
          name: {{ .Chart.Name }}-init-pg-config
          defaultMode: 0744
      {{ if .Values.provider.gcp }}
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      {{ end }}
