apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kernel-ui.fullname" . }}
  labels:
    app: {{ template "kernel-ui.name" . }}
    chart: {{ template "kernel-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kernel-ui.name" . }}
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      {{ if .Values.kube2iam.enabled }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.app.iam.role }}
      {{ end }}
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      {{- include "aether-kernel-ui.initContainers" . | indent 6 }}
      containers:
        {{- include "aether-kernel-ui.extraContainers" . | indent 6 }}
      - name: ui
        # This default allows us to overwrite '.Chart.Version' through the command line
        image: "{{ .Values.app.repository }}:{{ .Values.app.tag | default .Chart.Version }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        args:
        - {{ .Values.app.command }}
        ports:
          - name: http
            containerPort: {{ .Values.app.port }}
            protocol: TCP
        {{- include "aether-kernel-ui.probes" . | indent 8 }}
        env:
        {{- include "aether-kernel-ui.env" . | indent 8 }}
        volumeMounts:
        - mountPath: /var/www/static
          name: static-assets-volume
      volumes:
      - name: {{ .Chart.Name }}
      - name: static-assets-volume
      - name: nginx-config
        configMap:
          name: {{ .Chart.Name }}-nginx-config
      - name: init-config
        configMap:
          name: {{ .Chart.Name }}-init-pg-config
          defaultMode: 0744
      {{ if .Values.provider.gcp }}
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      {{ end }}
