# Default values for generic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride:
fullnameOverride:

podAntiAffinity:
  enabled: true

app:
  name:
  db:
    secret: database-credentials
    host: 127.0.0.1
    user:
    name:
  secret:
  name:
  port: 5432
  command: start
  static_root: /var/www/static
  storage:
    bucket:
      credentialsSecret:

database:
  instance:

url:

image:
  repository:
  tag:
  pullPolicy: Always

nginx:
  enabled: false

service:
  type: Ingress
  port: 80

imagePullSecrets:
  enabled: false
  name:

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "75M"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: letsencrypt
  path: /
  hosts:
    - chart-example.local
  ssl:
    letsencrypt: true
    cert_secret: wildcard

extra_env_vars: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
