# Default values for generic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Support for deployment and statefulset resource types
resourceType: deployment

replicaCount: 3

nameOverride:
fullnameOverride:

podAntiAffinity:
  enabled: true

# Additional init containers, e. g. for a database proxy, such as Google's cloudsql-proxy
extraInitContainers: |

# Additional sidecar containers, e. g. for a database proxy, such as Google's cloudsql-proxy
extraContainers: |

## Add additional volumes and mounts
extraVolumes: |

app:
  name:
  db:
    type: postgres
    create: false
    enabled: false
    secret: database-credentials
    ssl:
      enabled: false
    host: 127.0.0.1
    port: 5432
    user:
    name:
  secret:
  port:
  arg:
    enabled: true
    command:
    - start
  static_root: /var/www/static
  storage:
    bucket:
      credentialsSecret:
  probe:
    type: request
    # type: tcp
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
  volume:
    enabled: false
    mountPath:
    persist: false
    accessMode: ReadWriteOnce
    size: 10Gi

database:
  instance:

url:

gcp: true

image:
  repository:
  tag:
  pullPolicy: Always

nginx:
  enabled: false

service:
  type: NodePort
  externalPort:
  internalPort:

imagePullSecrets:
  enabled: false
  name:

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "75M"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: letsencrypt
    monitor.stakater.com/enabled: "true"
    statuscake.monitor.stakater.com/contact-group: "DevOps"

  path: /
  hosts:
    - chart-example.local
  ssl:
    letsencrypt: true
    cert_secret: wildcard

extra_env_vars: {}

env_secrets:
  enabled: false
  name:

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
