version: 2
jobs:
  build:
    docker:
      - image: alpine/helm:2.13.1

    steps:
      - checkout

      - run:
          name: gather
          command: helm lint -f tests/overrides/service.yaml src/gather/
      - run:
          name: aether-kernel
          command: helm lint -f tests/overrides/service.yaml src/aether-kernel/
      - run:
          name: aether-odk
          command: helm lint -f tests/overrides/service.yaml src/aether-odk/
      - run:
          name: aether-producer
          command: helm lint -f tests/overrides/service.yaml src/aether-producer/
      - run:
          name: aether-ui
          command: helm lint -f tests/overrides/service.yaml src/aether-ui/
      - run:
          name: aether-elasticsearch-consumer
          command: helm lint -f tests/overrides/service.yaml src/aether-elasticsearch-consumer/
