version: 2
jobs:
  build:
    docker:
      - image: alpine/helm:3.10.0

    steps:
      - checkout
      - run:
          name: database-provisioner
          command: helm lint -f tests/overrides/service.yaml src/database-provisioner/
      - run:
          name: kong
          command: helm lint -f src/kong/ci/values.yaml src/kong/
      - run:
          name: generic
          command: helm lint -f src/generic/ci/values.yaml src/generic/
      - run:
          name: opendistro-es
          command: helm lint src/opendistro-es/
      - run:
          name: generic
          command: helm lint src/generic/
      - run:
          name: generic3
          command: helm lint src/generic3/
