{{- if and .Values.ingressController.enabled .Values.ingressController.installCRDs -}}
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1"}}
apiVersion: apiextensions.k8s.io/v1beta1
{{- else }}
apiVersion: apiextensions.k8s.io/v1
{{- end }}
kind: CustomResourceDefinition
metadata:
  name: kongcredentials.configuration.konghq.com
  labels:
    app: {{ template "kong.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  group: configuration.konghq.com
  version: v1
  scope: Namespaced
  names:
    kind: KongCredential
    plural: kongcredentials
  additionalPrinterColumns:
  - name: Credential-type
    type: string
    description: Type of credential
    JSONPath: .type
  - name: Age
    type: date
    description: Age
    JSONPath: .metadata.creationTimestamp
  - name: Consumer-Ref
    type: string
    description: Owner of the credential
    JSONPath: .consumerRef
  validation:
    openAPIV3Schema:
      required:
      - consumerRef
      - type
      properties:
        consumerRef:
          type: string
        type:
          type: string
{{- end -}}
