apiVersion: v1
kind: Service
metadata:
  name: {{ template "kong.fullname" . }}-admin
  annotations:
    {{- range $key, $value := .Values.kong.admin.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    app: {{ template "kong.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.kong.admin.type }}
  {{- if eq .Values.kong.admin.type "LoadBalancer" }}
  {{- if .Values.kong.admin.loadBalancerIP }}
  loadBalancerIP: {{ .Values.kong.admin.loadBalancerIP }}
  {{- end }}
  {{- if .Values.kong.admin.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.kong.admin.loadBalancerSourceRanges }}
  - {{ $cidr }}
  {{- end }}
  {{- end }}
  {{- end }}
  ports:
  - name: kong-admin
    port: {{ .Values.kong.admin.servicePort }}
    targetPort: {{ .Values.kong.admin.containerPort }}
  {{- if (and (eq .Values.kong.admin.type "NodePort") (not (empty .Values.kong.admin.nodePort))) }}
    nodePort: {{ .Values.kong.admin.nodePort }}
  {{- end }}
    protocol: TCP
  selector:
    app: {{ template "kong.name" . }}
    release: {{ .Release.Name }}
    component: app
