# Default values for gather.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
pullPolicy: IfNotPresent
gather:
  repository: "ehealthafrica/gather"
  # Use `--set image.tag` in the command line to overwrite the version
  # tag: {{ .Chart.AppVersion }}
name: gather
project: aether
service:
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 80
environment: "dev"
ums_url: ums-dev
kernel_url: http://kernel
kernel_url_test: http://kernel
domain: gather.local
trusted_origins: gather.local, .aether.local
debug: false
testing: false
webserverPort: 8000
namespace:
  create: false
app:
  command: start
  secret: secrets
  data_mount: /media
  admin_user: admin
database:
  secret: database-credentials
provider:
  aws: false
ingress:
  enabled: true
  hosts:
    - gather.aether.local
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
