# Default values for gather.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
pullPolicy: Always
image:
  repository: "ehealthafrica/gather"
  # Use `--set image.tag` in the command line to overwrite the version
  # tag: {{ .Chart.AppVersion }}
name: gather
environment: "prod"
ums_url: ""
debug: false
testing: false
namespace:
  create: false
app:
  command: start
  secret: gather-secrets
  admin_user: admin
provider:
  aws: false
  gcp: false
