pullPolicy: Always
gw:
  env: dev
  pullPolicy: 'Always'
  repository: 'ehealthafrica/gateway-manager'
  debug: null
  tag: 'latest'
  command: ["/code/aether/initialize.sh"]
  aether:
    services: ["odk", "ui", "kernel", "gather"]
    ui:
      internalService: ''
    odk:
      internalService: ''
    kernel:
      internalService: ''
    gather:
      internalService: ''
  keyCloak:
    globalAdmin: 'keycloak'
    kongClient: ''
    aetherClient: 'aether' 
    baseDomain: ''
    baseHost: ''
    internalService: ''
  kong:
    internalService: ''
