apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
data:
  local.ini: |
    ; A locked couchdb uuid is important to keep replication checkpoints
    ; across redeploys!
    ; this will be needed in production as well!
    ; https://github.com/eHealthAfrica/ehealth-deployment/issues/512
    [couchdb]
    uuid = aaeba0036be60b8d51e405f697c0ef52

    [couch_httpd_auth]
    timeout = 1209600
