apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-sync-init
data:
  init.sh: |
    #!/bin/bash

    psql -c "CREATE DATABASE $DB_NAME;"
    psql -c "CREATE USER $DB_USERNAME WITH PASSWORD '$DB_PASSWORD';"
    psql -c "ALTER DATABASE $DB_NAME OWNER TO $DB_USERNAME;"
    psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USERNAME;"
