# Default values for couchdb-sync.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
pullPolicy: IfNotPresent
couchdbsync:
  repository: "ehealthafrica/aether-couchdb-sync"
  # Use `--set image.tag` in the command line to overwrite the version
  # tag: {{ .Chart.AppVersion }}
name: couchdb-sync
project: aether
service:
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 80
environment: "dev"
ums_url: ums-dev
kernel_url: http://kernel
kernel_url_test: http://kernel
domain: aether.local
trusted_origins: .aether.local
debug: false
testing: false
webserverPort: 8000
namespace:
  create: false
redis:
  name: redis
  data_mount: /data
  host: redis
  port: 6379
  db: couchdb-sync
couchdb:
  name: couchdb
  image:
    repository: couchdb
    tag: 1.7.1
  ## Sidecar that connects the individual Pods into a cluster
  helperImage:
    repository: kocolosk/couchdb-statefulset-assembler
    tag: 1.1.0
    pullPolicy: IfNotPresent
  url: http://couchdb:5984
  user: admin
  port: 5484
  clusterSize: 1
  podManagementPolicy: Parallel
  ## erlangFlags is a map that is passed to the Erlang VM as flags using the
## ERL_FLAGS env. `name` and `setcookie` flags are minimally required to
## establish connectivity between cluster nodes.
## ref: http://erlang.org/doc/man/erl.html#init_flags
  erlangFlags:
    name: couchdb
    setcookie: monster
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  # limits:
  #  cpu: 56
  #  memory: 256Gi
app:
  command: start
  secret: couchdb-sync-secrets
  data_mount: /media
  admin_user: admin
database:
  secret: database-credentials
provider:
  aws: false
ingress:
  enabled: true
  hosts:
    - couchdb-sync.aether.local
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
