replicaCount: 3
pullPolicy: Always
environment: "prod"
debug: false
ums_url: ""
image:
  repository: "ehealthafrica/aether-couchdb-sync"
app:
  command: start
  setup_command: setup
  secret: couchdb-sync-secrets
  admin_user: admin
  port: 8000
  db:
    name:
    host:
    user:
