# Default values for geoserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
application:
  secret: secrets
  data_mount: /opt/geoserver/data_dir

url_prefix: kaduna-geoserver
domain: ehealthafrica.org 

image:
  repository: kartoza/geoserver
  tag: 2.13.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - geoserver-kaduna.ehealthafrica.org
  tls:
   - secretName: ehealthafrica-wildcard
     hosts:
       - geoserver-kaduna.ehealthafrica.org

ingress:
  enabled: true
  certsecret: ehealthafrica-wildcard
  hosts:
    - odk.aether.local
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: "nginx"



database:
  secret: database-credentials
  instance:


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
