apiVersion: v1
kind: ConfigMap
metadata:
  name: firebase-consumer-kafka-config
data:
    kafka.json: |
      {
        "security.protocol": "SASL_SSL",
        "sasl.mechanism": "PLAIN",
        "group.id": "firebase-metadataonly",
        "auto.offset.reset" : "earliest",
        "enable.auto.commit": true,
        "auto.commit.interval.ms": 5000,
        "aether_emit_flag_required" : false,
        "aether_masking_schema_levels" : ["false", "true"],
        "aether_masking_schema_emit_level": "false",
        "heartbeat.interval.ms": 3000,
        "session.timeout.ms": 18000,
        "request.timeout.ms": 30000,
        "max.poll.interval.ms": 300000
      }
