apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ template "aether-elasticsearch-consumer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: es-consumer
          # This default allows us to overwrite '.Chart.Version' through the command line
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          args:
          - {{ .Values.app.command }}
          ports:
          - name: http
            containerPort: {{ .Values.app.port }}
            protocol: TCP
          livenessProbe:
            initialDelaySeconds: 300
            httpGet:
              path: /health
              port: http
              httpHeaders:
              - name: X-Kubernetes-Health-Check
                value: livenessProbe
          readinessProbe:
            initialDelaySeconds: 300
            httpGet:
              path: /health
              port: http
              httpHeaders:
              - name: X-Kubernetes-Health-Check
                value: readinessProbe
          env:
          - name: REDIS_DB
            value: {{ .Values.app.redis.db | quote }}
          - name: REDIS_HOST
            value: {{ .Release.Name }}-redis-master
          - name: REDIS_PORT
            value: {{ .Values.app.redis.port | quote }}
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-redis
                key: redis-password
          - name: ELASTICSEARCH_URL
            value: {{ .Values.app.elasticsearch.url }}
          - name: ELASTICSEARCH_USER
            value: {{ .Values.app.elasticsearch.user }}
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.app.secret }}
                key: elasticsearch-password
          - name: KIBANA_URL
            value: {{ .Values.app.kibana.url }}
          - name: KAFKA_URL
            value: {{ .Values.app.kafka.url }}
          - name: KAFKA_CONSUMER_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.app.secret }}
                key: kafka-su-username
          - name: KAFKA_CONSUMER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.app.secret }}
                key: kafka-su-password
          - name: TENANCY_HEADER
            value: {{ .Values.app.tenancyHeader }}
          - name: CONSUMER_NAME
            value: {{ .Values.app.consumerName }}
          - name: ES_CONSUMER_CONFIG_PATH
            value: {{ .Values.app.esConsumerConfigPath }}
          - name: ES_CONSUMER_KAFKA_CONFIG_PATH
            value: {{ .Values.app.esConsumerKafkaConfigPath }}
          - name: EXPOSE_PORT
            value: {{ .Values.app.port | quote }}
          - name: STACKDRIVER_LOGGING
            value: {{ .Values.app.stackDriverLogging | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.app.logLevel }}
          - name: CONSUMER_PORT
            value: {{ .Values.app.port | quote }}
          volumeMounts:
          - name: consumer-kafka-config
            mountPath: /code/conf/consumer/kafka.json
            subPath: kafka.json
          - name: consumer-config
            mountPath: /code/conf/consumer/consumer.json
            subPath: consumer.json
      volumes:
      - name: consumer-kafka-config
        configMap:
          name: consumer-kafka-config
          defaultMode: 0744
      - name: consumer-config
        configMap:
          name: consumer-config
          defaultMode: 0744

