{{ if and (.Values.app.scaling.enabled) (ne .Values.resourceType "cronjob") }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "generic.fullname" . }}
  labels:
    app: {{ template "generic.name" . }}
    chart: {{ template "generic.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.resourceType }}
    name: {{ template "generic.fullname" . }}
  minReplicas: {{ .Values.app.scaling.min }}
  maxReplicas: {{ .Values.app.scaling.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.app.scaling.utilization.cpu }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.app.scaling.utilization.memory }}

  {{ end }}
