{{ if eq .Values.app.replica.enabled "true" }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "generic.fullname" . }}
  labels:
    app: {{ template "generic.name" . }}
    chart: {{ template "generic.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.resourceType }}
    name: {{ template "generic.fullname" . }}
  minReplicas: {{ .Values.app.replica.min }}
  maxReplicas: {{ .Values.app.replica.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.app.replica.utilization.cpu }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.app.replica.utilization.memory }}

  {{ end }}