{{ if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "generic.fullname" . }}-nginx-config
data:
  default.conf: |
{{ tpl .Values.nginx.config . | indent 4 }}
{{ end }}
