{{- if gt .Values.replicaCount 1.0 -}}
{{- if .Values.app.minAvailable -}}

{{- if .Capabilities.APIVersions.Has "policy/v1beta1"}}
apiVersion: policy/v1beta1
{{- else }}
apiVersion: policy/v1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: "{{ template "generic.fullname" . }}-pdb"
  labels:
    app: "{{ template "generic.name" . }}-pdb"
    chart: {{ template "generic.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  minAvailable: {{ .Values.app.minAvailable }}
  selector:
    matchLabels:
      app: {{ template "generic.name" . }}
      release: {{ .Release.Name }}

{{- end }}
{{- end }}
