{{ if .Values.service_internal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "generic.fullname" . }}-internal
  labels:
    app: {{ template "generic.name" . }}
    chart: {{ template "generic.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service_internal.service.name }}
    port: {{ .Values.service_internal.service.externalPort }}
    targetPort: {{ .Values.service_internal.service.internalPort }}
    protocol: TCP

  selector:
    app: {{ template "generic.name" . }}
    release: {{ .Release.Name }}

{{ end }}
