{{- if .Values.traefik.enabled }}
{{- range $i, $mw := .Values.traefik.middleware }}
{{- if $i }}
---
{{ end }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $mw.name }}
  labels:
    app: {{ template "generic.name" $ }}
    chart: {{ template "generic.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  {{- toYaml $mw.spec | nindent 2 }}
{{- end }}
{{- end }}
