{{- if .Values.vaultextrasecrets.enabled -}}
{{- $fullname := include "generic.fullname" . -}}
{{- $chart := include "generic.chart" . -}}
{{- $release := .Release.Name -}}
{{- $service := .Release.Service -}}
{{- $mount := .Values.vaultStaticSecret.mount | default "kv" -}}
{{- $type := .Values.vaultStaticSecret.type | default "kv-v2" -}}
{{- $refreshAfter := .Values.vaultStaticSecret.refreshAfter | default "60s" -}}
{{- $vaultAuthRef := .Values.vaultStaticSecret.vaultAuthRef | default "vault-secrets-operator-system/default" -}}
{{- $rolloutrestart := .Values.vaultextrasecrets.rolloutrestart -}}
{{- range .Values.vaultextrasecrets.secrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .name }}
  labels:
    app: {{ $fullname }}
    chart: {{ $chart }}
    heritage: {{ $service }}
    release: {{ $release }}
spec:
  vaultAuthRef: {{ $vaultAuthRef }}
  mount: {{ $mount }}
  type: {{ $type }}
  path: {{ .path }}
  refreshAfter: {{ $refreshAfter }}
  hmacSecretData: true
  destination:
    name: {{ .name }}
    create: true
  {{- if .restartTargets }}
  rolloutRestartTargets:
    {{- range .restartTargets }}
    - kind: {{ .kind | default "Deployment" }}
      name: {{ .name }}
    {{- end }}
  {{- else if $rolloutrestart }}
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ $fullname }}
  {{- end }}
{{- end }}
{{- end }}
