{{- if .Values.vaultStaticSecret.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.env_secrets.name }}
  labels:
    app: {{ template "generic.fullname" . }}
    chart: {{ template "generic.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  vaultAuthRef: {{ .Values.vaultStaticSecret.vaultAuthRef }}
  mount: {{ .Values.vaultStaticSecret.mount }}
  type: {{ .Values.vaultStaticSecret.type }}
  path: {{ .Values.env_secrets.path }}
  refreshAfter: {{ .Values.vaultStaticSecret.refreshAfter }}
  destination:
    name: {{ .Values.env_secrets.name }}
    create: {{ .Values.vaultStaticSecret.destinationCreate }}
  {{- if .Values.vaultStaticSecret.rolloutRestart }}
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ template "generic.fullname" . }}
  {{- end }}
{{- end }}
