apiVersion: v1
# Must exist in https://hub.docker.com/r/ehealthafrica/aether-kernel/tags/
appVersion: "0.9.0-rc"
description: eHealthAfrica's Aether-Kernel Helm chart
name: aether-kernel
version: 0.0.3
