replicaCount: 3
pullPolicy: Always
environment: "prod"
debug: false
ums_url: ""

image:
  repository: "ehealthafrica/aether-kernel"

app:
  command: start
  setup_command: setup
  secret: kernel-secrets
  admin_user: admin
  port: 8000
  db:
    name:
    host:
    port:
    user:
    readonly_user: readonlyuser
