replicaCount: 3
pullPolicy: Always
environment: "prod"
debug: false
ums_url: ""

image:
  repository: "ehealthafrica/aether-kernel"

app:
  command: start
  secret: kernel-secrets
  admin_user: admin
  readonly_user: readonlyuser
  port: 8000
