replicaCount: 3
pullPolicy: Always
debug: false
ums_url: ""

kernel:
  repository: "ehealthafrica/aether-kernel-testing"
  tag: "mourino"

app:
  command: start
  setup_command: setup
  secret: kernel-secrets
  admin_user: admin
  port: 8000
  db:
    name:
    host:
    port:
    user:
    readonly_user: readonlyuser
