replicaCount: 3
pullPolicy: Always
debug: false
ums_url: ""

app:
  command: start
  setup_command: setup
  secret: kernel-secrets
  admin_user: admin
  repository: "ehealthafrica/aether-kernel"
  port: 8000
  db:
    name:
    host:
    port:
    user:
    readonly_user: readonlyuser
  url: kernel
service:
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 80
