{{- if and .Values.elasticsearch.client.ingress.enabled .Values.elasticsearch.client.enabled -}}
{{- $fullName := printf "%s-%s"  (include "opendistro-es.fullname" .) "client-service" }}
{{- $ingressPath := .Values.elasticsearch.client.ingress.path -}}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ $fullName }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
{{- with .Values.elasticsearch.client.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.elasticsearch.client.ingress.tls }}
  tls:
  {{- range .Values.elasticsearch.client.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.elasticsearch.client.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end -}}
{{- end -}}
