# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
{{- if .Values.elasticsearch.data.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
    role: data
  name: {{ template "opendistro-es.fullname" . }}-data-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 9300
    name: transport
  - port: 9200
    name: http
  - port: 9600
    name: metrics
  clusterIP: None
  selector:
    role: data
{{- end }}