apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "opendistro-es.fullname" . }}-security-config
data:
  config.yml: |
    _meta:
      type: "config"
      config_version: 2

    config:
      dynamic:
        kibana:
          multitenancy_enabled: true
          server_username: admin
        http:
          anonymous_auth_enabled: false
          xff:
            enabled: true
            internalProxies: '.*' # trust all internal proxies, regex pattern
            remoteIpHeader:  'x-forwarded-for'

        authc:
          basic_internal_auth_domain:
            http_enabled: true
            transport_enabled: true
            order: 0
            http_authenticator:
              type: basic
              challenge: false
            authentication_backend:
              type: intern

          proxy_auth_domain:
            http_enabled: true
            transport_enabled: true
            order: 1
            http_authenticator:
              type: proxy
              challenge: false
              config:
                user_header: "x-oauth-preferred_username"
                roles_header: "x-oauth-realm"
            authentication_backend:
              type: noop
