apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ template "kernel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  progressDeadlineSeconds: 180
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: init
        image: postgres:9.3-alpine
        command: ['bash', '-c', './scripts/init.sh']
        env:
        - name: PGHOST
          valueFrom :
            secretKeyRef:
              name: database-credentials
              key: host
        - name: PGUSER
          valuefrom:
            secretkeyref:
              name: database-credentials
              key: user
        - name: PGPASSWORD
          valuefrom:
            secretkeyref:
              name: database-credentials
              key: password
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-name
        volumeMounts:
        - mountPath: /scripts
          name: kernel-init-config
        {{ if .Values.provider.gcp }}
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        {{ end }}
      containers:
      {{ if .Values.provider.gcp }}
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances={{ .Values.database.instance }}=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      {{ end }}
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: {{ .Values.service.externalPort }}
        volumeMounts:
        - mountPath: /var/www/static
          name: static-assets-volume
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
        - mountPath: /media
          name: media
      - name: kernel
        image: "{{ .Values.kernel.repository }}:{{ .Values.kernel.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - {{ .Values.app.command }}
        ports:
        - name: http
          containerPort: {{ .Values.app.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
            httpHeaders:
            - name: X-Kubernetes-Health-Check
              value: livenessProbe
            - name: Host
              value: {{ .Release.Name }}.{{ .Values.domain }}
        readinessProbe:
          httpGet:
            path: /health
            port: http
            httpHeaders:
            - name: X-Kubernetes-Health-Check
              value: readinessProbe
            - name: Host
              value: {{ .Release.Name }}.{{ .Values.domain }}
        env:
        - name: DEBUG
          value: {{ if .Values.debug }}"1"{{ else }}""{{ end }}
        - name: CAS_SERVER_URL
          value: {{ .Values.ums_url }}
        - name: CSRF_COOKIE_DOMAIN
          value: {{ .Values.domain }}
        - name: CSRF_TRUSTED_ORIGINS
          value: .{{ .Values.domain }}
        - name: HOSTNAME
          value: {{ .Release.Name }}.{{ .Values.domain }}
        - name: MEDIA_ROOT
          value: "/media"
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-secret-key
        - name: ADMIN_USERNAME
          value: {{ .Values.app.admin_user }}
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-admin-password
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-admin-token
        - name: AETHER_KERNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-django-admin-token
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-password
        - name: PGPORT
          value: "5432"
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-user
        - name: PGHOST
          valueFrom :
            secretKeyRef:
              name: {{ .Values.database.secret }}
              key: host
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-database-name
        - name: KERNEL_READONLY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-readonly-db-password
        - name: KERNEL_READONLY_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.secret }}
              key: kernel-readonly-db-user
        - name: TESTING
          value: {{ quote .Values.testing }}
        # `WEB_SERVER_PORT` is kept around for compatibility with the old tests,
        # which are using different ports in different environments. Once all
        # tests have been updated to run inside the cluster, `WEB_SERVER_PORT`
        # can be removed.
        - name: WEB_SERVER_PORT
          value: {{ quote .Values.app.port }}
        - name: DJANGO_STORAGE_BACKEND
          value: {{ .Values.app.django_storage_backend }}
        {{- if (.Values.provider.aws) or (.Values.provider.gcp) }}
        - name: BUCKET_NAME
          value: {{ .Values.project }}-aether-{{ .Release.Name }}-upload
        {{ end }}
        volumeMounts:
        - mountPath: /var/www/static
          name: static-assets-volume
        - mountPath: /media
          name: media
        {{ if .Values.provider.gcp }}
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        {{ end }}
      volumes:
      - name: static-assets-volume
        emptyDir: {}
      - name: media
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: kernel-init-config
        configMap:
          name: kernel-init-config
          defaultMode: 0744
      {{ if .Values.provider.gcp }}
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      {{ end }}
